version: '3.9'

services:
  # Servicio de base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: pyacademy-db
    environment:
      POSTGRES_DB: pyacademy_db
      POSTGRES_USER: pyacademy_user
      POSTGRES_PASSWORD: pyacademy_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pyacademy_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servicio de aplicaci√≥n Django
  web:
    build: .
    container_name: pyacademy-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-dxl%&p_1fhc&u4an@=t)61!ed*!sw0f_b_whe&v2i+%7t_&)$#
      - DATABASE_URL=postgresql://pyacademy_user:pyacademy_password@db:5432/pyacademy_db
      - NEWS_API_KEY=${NEWS_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  static_volume:
  media_volume: